name: PR-test

on: [pull_request]

jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npx vitest --project node 